# name: "user_web"
# port: 8021

host: "go-nacos"
port: 8848
namespace: "98a14936-c8c5-4da6-966e-25c75305326b"
user: "nacos"
password: "nacos"
dataid: "user-web.json"
group: "dev"
# user_srv:
#   host: "127.0.0.1"
#   port: 50051
#   name: "user_srv"
# jwt:
#   key: "!4eir7w"
# sms:
#   key: ""
#   secret: ""
#   expire: 300
# redis:
#   host: "go-redis"
#   port: 6379
# consul:
#   host: "go-consul"
#   port: 8500